version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - 6432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schellar_test
