// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateScheduleInput struct {
	Name            string `json:"name"`
	Enabled         bool   `json:"enabled"`
	ParallelRuns    bool   `json:"parallelRuns"`
	WorkflowName    string `json:"workflowName"`
	WorkflowVersion string `json:"workflowVersion"`
	CronString      string `json:"cronString"`
	WorkflowContext string `json:"workflowContext"`
	FromDate        string `json:"fromDate"`
	ToDate          string `json:"toDate"`
}

type DeleteScheduleInput struct {
	Name string `json:"name"`
}

type Schedule struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Enabled         bool   `json:"enabled"`
	ParallelRuns    bool   `json:"parallelRuns"`
	WorkflowName    string `json:"workflowName"`
	WorkflowVersion string `json:"workflowVersion"`
	CronString      string `json:"cronString"`
	WorkflowContext string `json:"workflowContext"`
	FromDate        string `json:"fromDate"`
	ToDate          string `json:"toDate"`
	Status          string `json:"status"`
}

type UpdateScheduleInput struct {
	Name            string `json:"name"`
	Enabled         bool   `json:"enabled"`
	ParallelRuns    bool   `json:"parallelRuns"`
	WorkflowName    string `json:"workflowName"`
	WorkflowVersion string `json:"workflowVersion"`
	CronString      string `json:"cronString"`
	WorkflowContext string `json:"workflowContext"`
	FromDate        string `json:"fromDate"`
	ToDate          string `json:"toDate"`
}
