name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - 'master'
      - '[0-9]+.X-stable'

    # Publish `v1.2.3` tags as releases.
    tags:
      - 'v*'
      - 'v[0-9]+.[0-9]+.[0-9]-stable'

  # Run tests for any PRs.
  pull_request:
  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: frinx/schellar
  # DOCKER_CONTENT_TRUST: 1

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./test.sh

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build . --file Dockerfile --build-arg git_commit=$(git rev-parse HEAD) --tag $IMAGE_NAME

      - uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.IMAGE_NAME }}:latest
          # severity-threshold: CRITICAL

      #### Set tags based on source type ####

      - name: Set tag for latest image
        if: github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/master')
        run: |
          echo "IMAGE_TAG=$(echo 'latest')" >> "$GITHUB_ENV"

      - name: Set tag for stable-latest image
        if: github.ref_type == 'branch' && endsWith(github.ref, '-stable')
        run: |
          echo "IMAGE_TAG=$(echo 'stable-latest')" >> "$GITHUB_ENV"

      - name: Set tag for stable-release image
        if: github.ref_type == 'tag' && endsWith(github.ref, '-stable')
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_REF | cut -d / -f 3 | sed -e 's/^v-//' | sed -e 's/-stable//')" >> "$GITHUB_ENV"

      - name: Set tag for release image
        if: ${{ github.ref_type == 'tag' && !endsWith(github.ref, '-stable') }}
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_REF | cut -d / -f 3 | sed -e 's/^v-//')" >> "$GITHUB_ENV"

      - name: Push stable-release image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${IMAGE_TAG}
#          docker push $IMAGE_NAME:${IMAGE_TAG}

