name: Hive Publish

on:
  push:
    branches:
      - 'master'
      - '[0-9]+.X-stable'

    tags:
      - 'v*'
      - 'v[0-9]+.[0-9]+.[0-9]-stable'

  workflow_dispatch:

jobs:
  hive-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: schema publish
        env:
          HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
          HIVE_STABLE_LATEST_TOKEN: ${{ secrets.HIVE_STABLE_LATEST_TOKEN }}
          # HIVE_ENDPOINT: ${{ secrets.HIVE_ENDPOINT }}
          SCHEMA_PATH: "schellar/graph/schema.graphqls"

        if: github.ref_type == 'branch' && endsWith(github.ref, '-stable')
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
          hive schema:publish ${{ env.SCHEMA_PATH }} \
            --registry.accessToken ${{ env.HIVE_STABLE_LATEST_TOKEN }} \
            --github
